---
spring:
  application:
    name: "idempotent-batch"
  datasource:
    url: "jdbc:postgresql://localhost:5432/vienhuynhemc"
    username: "vien.huynh"
    password: "123456"
    driver-class-name: "org.postgresql.Driver"
  batch:
    job:
      enabled: false
