---
spring:
  application:
    name: "outbox-pattern"
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
      acks: "all"
      retries: 5
      batch-size: 32768
      compression-type: "snappy"
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        linger.ms: 5
        request.timeout.ms: 5000
        delivery.timeout.ms: 60000
  datasource:
    url: "jdbc:postgresql://localhost:5432/vienhuynhemc"
    username: "vien.huynh"
    password: "123456"
    driver-class-name: "org.postgresql.Driver"
